### ISSUE TITLE
[CCv1.8.9][SSP/SMP] Turtle Inventory GUI missing slots

### ISSUE THREAD

**Issue by exoskeleton500** [dan200/ComputerCraft#104] opened 2016-05-16 23:12 UTC
When right-clicking a Turtle in Spectator Mode (gamemode 3) the inventory GUI that pops up has only the first 9 slots, not the full 16.

https://imgur.com/a/s3elO

**Comment by KnightMiner** [comment] 2016-05-16 23:36
Duplicate of #53.

**Comment by dan200** [comment] 2016-05-17 00:01
Yep. Also not high priority at all.

**Closed by dan200** 2016-05-17 00:01 UTC
