### ISSUE TITLE
IModel is deprecated

### ISSUE THREAD

**Issue by SquidDev** [dan200/ComputerCraft#21] opened 2015-12-09 19:35 UTC
Not actually a bug, but reporting anyway.

Forge has deprecated Minecraft's `IBakedModel` in favour of `net.minecraftforge.client.model.IFlexibleBakedModel` (used in the Turtle upgrades). Not sure though if there are issues with rendering a `IFlexibleBakedModel` compared with the original one.

For `getItemModel` you can always wrap the `IBakedModel` with `IFlexibleBakedModel.Wrapper`.

**Comment by dan200** [comment] 2015-12-10 00:34
I presume the issue is that ITurtleUpgrade.getModel returns IBakedModel, and this is triggering a warning when you compile your project? IFlexibleBakedModel inherits from IBakedModel, and the code that calls it is cable of handling either. The reason the return value is IBakedModels is to allow the user to implement either one, as most built-in models will simply be IBakedModel.

**Comment by SquidDev** [comment] 2015-12-10 17:53
I guess the deprecation warning is more for implemeters rather consumers. To me it feels a bit odd using a deprecated interface in the API but it isn't a big issue.

**Comment by dan200** [comment] 2015-12-11 12:14
Toyed with changing this, but decided to keep it how it is, using ISmartBlockModel/ISmartItemModel as precedent. Closing.

**Closed by dan200** 2015-12-11 12:14 UTC
