### ISSUE TITLE
Missing pixels on turtle upgrades

### ISSUE THREAD

**Issue by SquidDev** [dan200/ComputerCraft#27] opened 2015-12-10 17:50 UTC
![](http://i.imgur.com/8WwieRd.png?1)

Not sure why this is happening, I guess you could disable backface culling.

**Comment by dan200** [comment] 2015-12-11 10:39
Can't reproduce this. Can you confirm this is a regular Mining Turtle (not your own upgrade), and that you don't have any resource packs installed that change the model of the pick?

**Comment by SquidDev** [comment] 2015-12-11 10:41
Normal upgrade with no resource packs in a dev environment. My computer is ancient so that may be something to do with it.

**Comment by dan200** [comment] 2015-12-11 10:42
Is there any upgrade attached to the other side of the turtle?

**Comment by SquidDev** [comment] 2015-12-11 10:43
In this case yes, but I can reproduce without one.

**Comment by dan200** [comment] 2015-12-11 10:45
Can you create a new superflat world, select a mining turtle from the creative menu, place it at your feet facing north, and tell me the co-ordinates of the turtle

**Comment by SquidDev** [comment] 2015-12-11 10:50
I'm not currently on my home computer - I'll have a go this evening. Sorry.

**Comment by dan200** [comment] 2015-12-11 10:53
No worries.

**Comment by apemanzilla** [comment] 2015-12-11 15:50
Also, do you by chance have advanced OpenGL enabled? I've had related problems with different mods, where some faces of a texture would disappear.

**Comment by SquidDev** [comment] 2015-12-11 18:40
Screenshot with debug view.
![](http://i.imgur.com/YroeOGz.png)

I tried a pickaxe in an item frame but that renders fine. I tried several other items(pork and steak) but they rendered correctly.

**Comment by dan200** [comment] 2015-12-12 00:00
Alright. I can't replicate this. Closing, but will re-open if anyone else reports it.

**Closed by dan200** 2015-12-12 00:00 UTC
