### ISSUE TITLE
[1.76pr2-3] External monitor rendering

### ISSUE THREAD

**Issue by BombBloke** [dan200/ComputerCraft#45] opened 2015-12-12 01:16 UTC
Tall monitors may bug out when viewed from specific angles / distances. The taller the display, the easier it is to reproduce; I find it needs to be at least 4 blocks high before I can trigger it. Compass direction does not appear to matter, but world height does.

To trigger, move close to the top of an affected display, then slowly tilt your view upwards.

For example, building a staircase of monitors at around y110, I get:

![2015-12-12_12 13 34](https://cloud.githubusercontent.com/assets/12162603/11759189/01a9e798-a0ca-11e5-8676-bf93ca75dbaf.png)

**Comment by dan200** [comment] 2015-12-13 17:08
I can't reproduce this. Can you try to produce the simplest possible repro case on a superflat world?

**Comment by BombBloke** [comment] 2015-12-13 23:43
Sure;

1. Make creative superflat.
2. Pillar monitors; up to about ~y120 should be plenty, facing any direction.
3. Tilt camera upwards and fly up/down the tower. Some monitors in the stack should blink out at certain heights.

I've got a couple of graphics cards in this system and I get the same results with each:

![2015-12-14_09 40 09](https://cloud.githubusercontent.com/assets/12162603/11769954/45ce7960-a247-11e5-8d7a-4a06d23c1a55.png)
![2015-12-14_10 42 04](https://cloud.githubusercontent.com/assets/12162603/11770325/625f047a-a24f-11e5-9484-058a535377ea.png)

**Comment by dirk1763** [comment] 2015-12-14 00:44
i got the same result with cloning the middle part out of a bigger monitor. I didnt post it yet because i could not think of any good reason why anybody would clone a monitor apart. Cloning the whole monitor worked.

**Comment by dan200** [comment] 2015-12-14 15:33
Bomb Bloke: Thanks for the repro steps, I managed to reproduce it. It seems to be happening when the bottom of the monitor is in one vertical chunk and the rest is in another. Minecraft/Forge doesn't seem to obey large TileEntity bounding boxes in these cases. I'll have a think about how to solve.

dirk1763: Do you mean cloning using the /clone command? If so, that'll stay broken: I don't intend to go down the rabbit hole of providing support for every way blocks and NBT can be manipulated with commands.

**Comment by dirk1763** [comment] 2015-12-14 15:41
Yeah, thats what i thought too. I was using the /clone command

**Comment by dan200** [comment] 2015-12-14 16:05
Fixed in 1.76pr4

**Closed by dan200** 2015-12-14 16:05 UTC
