### ISSUE TITLE
Monitors causing miscolouration of tile entities

### ISSUE THREAD

**Issue by half-cambodian-hacker-man** [dan200/ComputerCraft#349] opened 2017-07-03 23:44 UTC
Hey - with a monitor in the field of vision, the glColor does not get reset before rendering other tile entities, leading to things like chests being broken.

Here, green text is being drawn on a monitor under me, and the chests are green as well.

![image](https://user-images.githubusercontent.com/4404985/27810421-e8faaf04-6051-11e7-969c-f5090d106088.png)

And here, with the monitor out of frame, the chests return to normal colour.

![image](https://user-images.githubusercontent.com/4404985/27810416-decfdde2-6051-11e7-857f-815a61427781.png)

I think this can easily be fixed by running a glColor3f(1, 1, 1) after you've rendered monitors.

**Comment by BombBloke** [comment] 2017-07-04 00:36
Worth noting that this doesn't trigger on all systems - I suspect drivers are a factor, as I've seen a Windows 10 / Nvidia system do it (newer hardware & newer drivers) and a Windows 8.1 / Nvidia system avoid it (older hardware & older drivers).

**Comment by half-cambodian-hacker-man** [comment] 2017-07-04 00:37
Alright - I'm on Linux / Nvidia with latest proprietary drivers.

**Comment by SquidDev** [comment] 2017-07-04 11:36
It's worth noting that it already calls [`GlStateManager.color`](https://github.com/dan200/ComputerCraft/blob/master/src/main/java/dan200/computercraft/client/render/TileEntityMonitorRenderer.java#L291) after rendering. However, this may not have any effect as I believe `glCallList` will change OpenGL's colour, but not the colours in `GLStateManager`. Adding a call to `GLStateManager.resetColor()` after each call to `GLStateManager.callList` *should* fix it - I've been unable to reproduce so could someone else test this?

**Comment by DevelopedLogic** [comment] 2017-07-05 06:26
So it isn't just me. Good. @SquidDev I'm able to reproduce this with both signs and chests on the same server - Airwaves. Running AMD graphics.

**Comment by SquidDev** [comment] 2017-07-05 07:00
@DevelopedLogic Could you try with the file [linked here](https://github.com/dan200/ComputerCraft/pull/351#issuecomment-312963231) and confirm it works?

**Comment by DevelopedLogic** [comment] 2017-07-05 07:06
@SquidDev I can, however it will be several hours before I can do so. I'm out now so will do it ASAP.

**Comment by SquidDev** [comment] 2017-07-05 07:20
@DevelopedLogic It's just for 1.9.4-1.10.2 currently. Though if the bug manifests on 1.11, it'll also appear on 1.10.

**Comment by DevelopedLogic** [comment] 2017-07-05 19:04
@SquidDev I have tested, and I can confirm this issue exists in 1.12 .  The screenshots the OP provided were in Airwaves, which was 1.11 at the time, meaning the issued existed in 1.11 . Airwaves is now 1.12 and I still get it.
![2017-07-05_20 00 23](https://user-images.githubusercontent.com/28887353/27880413-c8a81e32-61bc-11e7-9a17-88a8e92b073b.png)

Interestingly, I only seem to have the issue when the monitor renders a colour which is not normal, aka one which has been created via setPaletteColour. No matter what angle I go at it, the issue doesn't occur with the default red colour.
![2017-07-05_20 03 23](https://user-images.githubusercontent.com/28887353/27880508-1d03d73c-61bd-11e7-8b75-65736a5e9eca.png)

**Comment by SquidDev** [comment] 2017-07-05 19:42
@DevelopedLogic The bug hasn't been fixed in the Airwaves version of ComputerCraft - you'll need to download the above version and test in a 1.10 world.

**Comment by Wojbie** [comment] 2017-07-05 19:48
To explain better - It will not get fixed until this PR gets merged.

**Closed** 2017-07-25 18:02 UTC
