### ISSUE TITLE
[1.80pr0] Monitor not working and texture bugg.

### ISSUE THREAD

**Issue by wdejonge97** [dan200/ComputerCraft#136] opened 2016-08-14 21:11 UTC
No further explanation needed. I do have a screenshot. Also saw that the computer is not turning on after    joinen the world, but someone already made a threat about it. (both tested on singeplayer and server.
![2016-08-14_23 03 22](https://cloud.githubusercontent.com/assets/21026786/17652094/6b7cc00c-6274-11e6-84c3-132104191471.png)

**Comment by negamartin** [comment] 2016-08-15 02:32
Seems like a duplicate of #123 ?

**Comment by wdejonge97** [comment] 2016-08-15 07:09
Looks like it. I looked if someone already reported this bugg but couldnt find it. Guess I missed it.

And I found another one. When you give turtle a turn command it doesnt turn until you right-click on it again. Than it turns.

**Comment by negamartin** [comment] 2016-08-15 19:03
That's also been reported on #113

**Comment by wdejonge97** [comment] 2016-08-16 19:16
I guess this can be closed then

**Comment by dan200** [comment] 2017-05-07 17:47
I believe this is fixed in current

**Closed by dan200** 2017-05-07 17:47 UTC

**Comment by fcpwiz** [comment] 2017-06-13 04:17
@dan200 Where can I find the files that contain the fix for this?

**Comment by vpontin** [comment] 2017-06-13 05:54
@fcpwiz you need to build the source yourself OR download from @SquidDev 's build system: https://cc.crzd.me/

**Comment by fcpwiz** [comment] 2017-06-13 12:51
Ah, thanks @vpontin !
