### ISSUE TITLE
East facing advanced turtles.

### ISSUE THREAD

**Issue by hugeblank** [dan200/ComputerCraft#73] opened 2015-12-22 00:17 UTC
When an advanced turtle is blown up facing the east, it turns north. When right clicked, it will resume facing east. A very minor bug, but nevertheless, an intresting one.

**Comment by dan200** [comment] 2015-12-22 00:18
Advanced turtles aren't supposed to be able to be blown up.. What did you
use to explode it?

**Comment by hugeblank** [comment] 2015-12-22 00:19
It doesn't blow up.

**Comment by hugeblank** [comment] 2015-12-22 00:20
When an explosion is triggered nearby it.

**Comment by dan200** [comment] 2015-12-22 00:20
You literally just said "is blown up". How did you trigger this bug?

**Comment by hugeblank** [comment] 2015-12-22 00:22
Yea, misspoke... I placed a turtle down facing east with TNT next to it. triggered the TNT, and once it exploded it immediately turned north.

**Comment by Wojbie** [comment] 2015-12-22 21:55
Reproduction steps:
1. Place a turtle with a peripheral (Mining works best visually)
2. Detonate TNT or creeper next to turtle.
3. Turtle will visually turn into peripheral-less version facing north
4. Any update to turtle (Like r-click) will make it restore to normal version.

**Comment by BombBloke** [comment] 2015-12-23 11:43
This is also a trigger for #62 (monitors bugging out until re-chunkloaded) - the key is that blocks in the area have to actually be changed. Planting a large collection of TNT blocks in an enclosed space underground is more effective then firing off a single one directly next to actual turtles (which are blast-proof), though some level of proximity seems to be required (presumably "same chunk").

**Comment by BombBloke** [comment] 2015-12-23 12:09
Here's a reproduction script for a command computer:

http://pastebin.com/d9EBFkx5

Before running it, place some turtles, other computers, and some multiblock monitors around the command computer (within the same chunk). It'll perform some block changes in an area about five blocks above, which should trigger the fault within a few seconds.

**Comment by dan200** [comment] 2016-01-15 17:13
Can you re-test this is 1.77pr0?

**Comment by Wojbie** [comment] 2016-01-15 17:20
Confirmed using with BombBloke code from 2 post up.
This and https://github.com/dan200/ComputerCraft/issues/62 seem to be same issue.

**Comment by dan200** [comment] 2016-01-15 17:28
Right-o. Closing as duplicate

**Closed by dan200** 2016-01-15 17:28 UTC
