### ISSUE TITLE
[1.80pr0] Jumbo-sized items

### ISSUE THREAD

**Issue by lurquhar1221** [dan200/ComputerCraft#116] opened 2016-06-28 08:42 UTC
The items below are jumbo-sized when held.
- All turtles.
- Pocket Computers.
- Floppy Disks
- Printed Page
- Printed Pages
- Printed Book
- All modems
- Networking Cable

Picture for reference http://i.imgur.com/mf4RfBW.png

( 1.9.4, Forge 12.17.0.1976, Java 1.8.0_65 64bit, no other mods loaded)

**Comment by eniallator** [comment] 2016-06-28 10:07
this is also the case for the item entity version of these items

**Comment by KnightMiner** [comment] 2016-06-28 12:53
Duplicate of #112

**Comment by dan200** [comment] 2016-07-04 11:08
Fixed in pr1

**Closed by dan200** 2016-07-04 11:08 UTC
