### ISSUE TITLE
[Suggestion] Increase graphics resolution

### ISSUE THREAD

**Issue by ScoutCD10** [dan200/ComputerCraft#213] opened 2017-05-07 15:49 UTC
Currently ComputerCraft has a resolution of 57x16 pixels.
I think that the resolution should be increased to like 320x200 giving more possiblities for new programs improving their graphics by a lot!

**Comment by Restioson** [comment] 2017-05-07 15:50
@dan200 said that it was to keep it retro.

**Comment by MaoamZedong** [comment] 2017-05-07 15:52
cc's resolution is 51x19

**Comment by SquidDev** [comment] 2017-05-07 16:10
This is kinda a duplicate of #188. It is something I'm considering PRing, but I think terminal network traffic should be optimised first.

**Comment by dan200** [comment] 2017-05-07 17:11
Well, technically the resolution of individually addressable "pixels" is 114*57 with the advanced drawing characters. But yeah: I'd like CC 1.x to keep a text mode interface. Gotta save something for CraftOS 2

**Comment by Restioson** [comment] 2017-05-08 15:08
+1. I think that the retroness simplifies it and makes it more approachable to newer players, which possibly increases its value as a learning tool.

**Comment by CrazedProgrammer** [comment] 2017-05-08 16:10
@dan200 correction: it's 102x57 pixels :P
I think it is good enough as it is, it brings creative UI designs and it contributes to the look and feel of ComputerCraft.

**Closed** 2017-05-08 16:52 UTC

**Comment by ScoutCD10** [comment] 2017-05-08 16:53
Ok i acknowledged the retroness thing and i think that the resolution should be kept for COS2.0 as said by Dan so i close the suggestion!
