### ISSUE TITLE
turtle.attack issues

### ISSUE THREAD

**Issue by dirk1763** [dan200/ComputerCraft#49] opened 2015-12-12 15:01 UTC
turtle.attack does not allways return true when there is a mob infront of it and it has a weapon.

Skeletons keep spooting at the spot where the turtle has been while attacking.
Creepers blow up, once they have been hit.

**Comment by dirk1763** [comment] 2015-12-12 15:38
works correct when the turtle is facing south
+.5 on x and +.5 on z facing east or west
+1 on x facing north or south
which means the turtle can not attack at all when it is facing north

**Comment by dan200** [comment] 2015-12-13 19:04
Fixed in 1.76pr4

**Closed by dan200** 2015-12-13 19:04 UTC

**Comment by BombBloke** [comment] 2015-12-23 12:36
I'm still seeing creepers exploding after turtles whack them in pr8.

Skeletons don't fight back, but rather turn and face the turtle's location from where the attack was performed (regardless as to whether the turtle is still there) and then remain stationary until death or despawn. Even punching them manually (as a player in survival mode) doesn't snap them out of this, though it does move them around to the extent you'd expect.

A zombie seems to have similar behaviour, attempting to path somewhere below the turtle?

**Comment by dan200** [comment] 2015-12-23 12:40
Creepers exploding when attacked is not a bug

**Comment by BombBloke** [comment] 2015-12-23 13:21
Ah. Well then.

In any case, I'm finding that they're having the same problem with "ghost turtles". If they get knocked away from that location by the strike (say down a pit), then like zombies, they attempt to path to somewhere below that point. They'll explode if they ever reach it (no matter how long that takes, or whether the turtle's still there when they arrive).

These behaviours are the same under MC 1.7.10 builds.

In other news, the 24th has ticked over in my timezone and my turtles took on their festive appearance. First time I've seen it in-game.
