### ISSUE TITLE
Monitor pixel errors

### ISSUE THREAD

**Issue by Lion4ever** [dan200/ComputerCraft#56] opened 2015-12-14 20:21 UTC
Reproduction:
 place two monitors next to each other and move sidewards infront of the monitors.
![t](https://cloud.githubusercontent.com/assets/8234006/11792669/8a8de18e-a2a7-11e5-8220-102a2eef7fdc.PNG)

the pixels allways have the text color that was last written there.
![asd](https://cloud.githubusercontent.com/assets/8234006/11792805/515daf2e-a2a8-11e5-8954-b29bae398367.PNG)
![ermit](https://cloud.githubusercontent.com/assets/8234006/11792863/9b9982d4-a2a8-11e5-8313-5599df5fd521.PNG)

**Comment by dan200** [comment] 2015-12-14 23:51
I can't reproduce this. If anyone else has seen it, can they post their graphics card info from the F3 screen?

**Comment by dan200** [comment] 2015-12-15 01:48
This may be fixed in pr5. Let me know!

**Comment by Lion4ever** [comment] 2015-12-15 02:46
It is not fixed in pr5.
My grafics card is ATI Radeon HD 4650 btw

**Comment by dan200** [comment] 2015-12-15 02:49
In which case: can you go back through the versions and tell me when it
first appears? Downloads are here:
http://minecraft.curseforge.com/projects/computercraft/files

**Comment by Lion4ever** [comment] 2015-12-15 03:25
ok, the title of this issue was wrong.
The first version that has the monitor flickering was 1.76pr0, so it may be a forge 1.8 thing.

I tested it in 1.75 and 1.74 too, the monitor was perfektly black there. But in that versions I had the problem that the game crashes when i join a world while looking at a monitor, which is luckily gone in all 1.76 version :+1: 
That crash was directly the fault of my grafics card driver...
Old error report: http://pastebin.com/fb3YTG42

So maybe i really am the only one having the flickering issue.

**Comment by BombBloke** [comment] 2015-12-15 11:19
I can't reproduce the flickering either. Got a weird shadowy effect under pr4, but it's gone under pr5. Prior to pr4 I was getting white dots, but I'm fairly sure they've shown up in all prior builds (even pre-MC1.8) and pr5 seems to've cleared them too.

It may be worth double checking that your graphics drivers are up to date. If you simply go in and download the "latest pack for your OS", then you'll not update the software for your (legacy) card at all. With AMD you need to use their Drivers & Downloads Center to get a download specific to your hardware, unless you've got something quite new.

However, the crash bug you encountered was never patched for some Radeon cards anyways; if you're one of the unlucky ones, the only answers are to either start testing older drivers (to find the one before they introduced the problem, a flaw within their OpenGL-related code), or get a different card.

**Comment by Lion4ever** [comment] 2015-12-15 16:07
i updated the driver with amds auto installer, but i still have the white dots...

i am going to buy a new grafics card then.

Thanks for your help BombBloke :+1:

**Closed** 2015-12-15 16:07 UTC

**Comment by BombBloke** [comment] 2015-12-15 23:38
I suspect you'll always have the white dots, but what about the coloured dots? What about the crashes?

**Comment by Lion4ever** [comment] 2015-12-16 09:51
whethere the dots are white or coloured is only depening on the textcolour that is currently set there.
The crashes were a minecraft 1.7.10 thing and did not happen in any 1.8 pr versions
