### ISSUE TITLE
Server Startup Crash

### ISSUE THREAD

**Issue by Creeper9207** [dan200/ComputerCraft#23] opened 2015-12-10 02:06 UTC
http://pastebin.com/NxzYjB2h
Always crashes opon startup

**Comment by columna1** [comment] 2015-12-10 02:24
duplicate of https://github.com/dan200/ComputerCraft/issues/22
please check closed issues before posting.

**Comment by dan200** [comment] 2015-12-10 02:43
Yep, this is fixed for 1.76pr1

**Closed by dan200** 2015-12-10 02:43 UTC
